% problem 2
iidata=readtable('hw2dataproblem2.txt')
iidata=table2array(iidata)
%question 1
idata=readtable('hw2dataproblem1.txt')
%% 

%curvefitter doesn't like that the first term is 0 so I am making an array
%of the data without the first row
xdataii=iidata(2:end,1)
yavgsii=[]
stdevsii=[]
uncertii=[]
for x=2:25 
    fillarrayii=iidata(x,2:end)
    avg=mean(fillarrayii)
    stdev=std(fillarrayii)
    uncertainty=stdev/24
    yavgsii=[yavgsii;avg]
    stdevsii=[stdevsii;stdev]
    uncertii=[uncertii;uncertainty]
end

[fitresult, gof] = createFit(xdataii, yavgsii)

%  General model Power1:
%      val(x) = a*x^b
%      Coefficients (with 95% confidence bounds):
%        a =       0.367  (0.3647, 0.3693)
%        b =     0.03033  (0.02743, 0.03323)

figure
y1=[]
y2=[]
for x=1:24
    
y1new=.367*xdataii(x)^.03033
y1=[y1;y1new]
end


for x=1:24
y2new=.02752*xdataii(x)
y2=[y2;y2new]

end
plot(xdataii,y2)

figure
plot(xdataii,y1)
hold on
errorbar(xdataii,yavgsii,uncertii)
%the fit is not particularly good, it only passes thru 3 of the arror bars
%

function [fitresult, gof] = createFit(xdataii, yavgsii)
%CREATEFIT(XDATAII,YAVGSII)
%  Create a fit.
%
%  Data for 'untitled fit 2' fit:
%      X Input: xdataii
%      Y Output: yavgsii
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 03-Mar-2023 19:49:05


%% Fit: 'untitled fit 2'.
[xData, yData] = prepareCurveData( xdataii, yavgsii );

% Set up fittype and options.
ft = fittype( 'power1' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.37229262107942 0.0227246270199283];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 2' );
h = plot( fitresult, xData, yData );
legend( h, 'yavgsii vs. xdataii', 'untitled fit 2', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'xdataii', 'Interpreter', 'none' );
ylabel( 'yavgsii', 'Interpreter', 'none' );
grid on
end
