sixdat=readtable("Analysis lab 6.csv")
%% 

xdat=sixdat(2:7,14)
ydat=sixdat(2:7,15)
%% 
xdat=table2array(xdat)
ydat=table2array(ydat)
reg=lsqr(xdat,ydat)
[fitresult, gof] = createFit(xdat, ydat)

function [fitresult, gof] = createFit(xdat, ydat)
%CREATEFIT(XDAT,YDAT)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input: xdat
%      Y Output: ydat
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 14-Mar-2023 22:47:57


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( xdat, ydat );

% Set up fittype and options.
ft = fittype( {'x', '1'}, 'independent', 'x', 'dependent', 'y', 'coefficients', {'a', 'b'} );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );

% Plot fit with data.
figure( 'Name', 'Line of best fit' );
h = plot( fitresult, xData, yData );
legend( h, 'Velocity vs. Displacement', 'Line of Best Fit', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'Displacement (microns)', 'Interpreter', 'none' );
ylabel( 'Velocity (microns/s)', 'Interpreter', 'none' );
grid on
end


